var ru = {
	title: '3snet - Бинарные опционы, форекс, гэмблинг - трафик, лиды, депозиты!',
	header_who_we: 'КТО МЫ',
	header_partners: 'НАШИ РЕКЛАМОДАТЕЛИ',
	header_contacts: 'КОНТАКТЫ',
	intro_text: 'Бинарные опционы, форекс, гэмблинг - трафик, лиды, депозиты!',
	content_title: 'Партнерская сеть 3snet предлагает',
	content_terms1: 'Форекс<br/>Бинарные опционы<br/>Гэмблинг<br>Беттинг<br>География - весь мир<br/>Схемы работы обсуждаются',
	content_terms2: 'Высокие ставки по офферам<br>Индивидуальные условия<br>Поддержку онлайн<br>Регулярные выплаты',
	content_terms3: 'Рекламодателям - трафик',
	content_terms4: 'Партнерам - отличные условия',
	enter: 'Войти',
	partners: 'Наши рекламодатели',
	contacts: 'Контакты',
	for_partners: 'Для партнёров',
	for_adverts: 'Для рекламодателей',
	show_full_list: 'Показать полный список',
	hide_full_list: 'Скрыть полный список',
	all_right_reserved: 'Копирайт'
};

var en = {
	title: '3snet - Binary options, forex, gambling - traffic, leads, deposits!',
	header_who_we: 'WHO WE ARE?',
	header_partners: 'OUR ADVERTISERS',
	header_contacts: 'CONTACTS',
	intro_text: 'Binary options, forex, gambling - traffic, leads, deposits!',
	content_title: 'CPL/CPA network 3snet offers',
	content_terms1: 'Forex<br/>Binary options<br/>Gambling<br/>Betting<br/>Geo - worldwide',
	content_terms2: 'High rates on offers<br/>Individual terms<br/>Online support<br/>Regular payments',
	content_terms3: 'Traffic for advertisers',
	content_terms4: 'Profitable terms for publishers',
	enter: 'Sign In',
	partners: 'Our advertisers',
	contacts: 'Contacts',
	for_partners: 'Publishers',
	for_adverts: 'Advertisers',
	show_full_list: 'Show full list',
	hide_full_list: 'Hide full list',
	all_right_reserved: 'Copyright'
};